### ISSUE TITLE
core dumped when run on MacOS with Apple Silicon

### ISSUE THREAD

**Issue by kevin1sMe** [soulteary/docker-chatgpt#3]
logs like this:
```bash
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Does it  support ARM?

**Comment by soulteary** [comment]
@kevin1sMe Thanks for the reminder, the next version will update the ARMv64 version of the program

**Comment by soulteary** [comment]
@kevin1sMe  da10915ac6c4c133307e80eef3d7a2750264afb2
try to use `soulteary/docker-chatgpt:arm64`
