### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by itxtl** [soulteary/docker-chatgpt#4]
MIDJOURNEY_API_SECRET: "123123"
      # => Midjourney API Address, eg: `"ws://...."`, or `"ws://host.docker.internal:8092/ws"`
      MIDJOURNEY_API_URL: "ws://localhost:8092/ws"

Do you need to set up the service locally by yourself? Are there any sample projects?

**Comment by soulteary** [comment]
that's a good question, the answer is yes. @itxtl 

You can implement a midjourney service yourself to accomplish this.

The implementation cost is not high, but limited by the user agreement, there may be some risks in public and private implementations.

**Comment by itxtl** [comment]
Do you have any reference projects? Or do we need to use direct HTTP connection? Sorry, I'm not very familiar with Go language.
